"""One-off generator for the known-answer vectors; the JSON is committed as a regression anchor.

It refuses to overwrite existing files: a vector that changes is no anchor.
``signature_v1.json`` is not produced here; it was generated by Pingobit, the
project hybride-pq was extracted from, and is kept verbatim.

Run from the repository root: python tests/vectors/generate_vectors.py
"""

import json
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric import mlkem, x25519
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

from hybride_pq import KeyPair, keystore
from hybride_pq.channel import AUTH_CONTEXT, MAGIC, _nonce, derive_keys, session_proof_message
from hybride_pq.sign import _sign

HERE = Path(__file__).parent
PASSPHRASE = "correct horse battery staple"
SIGNATURE_VECTOR = json.loads((HERE / "signature_v1.json").read_text())
FRAME_PLAINTEXT = b"pbp1 test vector: first frame"


def _write(name: str, make) -> None:
    path = HERE / name
    if path.exists():
        print(f"skipped (exists): {path}")
        return
    make(path)
    print(f"written: {path}")


def _keystore(path: Path) -> None:
    secret = bytes.fromhex(SIGNATURE_VECTOR["secret_bytes"])
    keystore.save(path, secret, PASSPHRASE)
    doc = json.loads(path.read_text())
    doc["test_passphrase"] = PASSPHRASE
    path.write_text(json.dumps(doc, indent=2) + "\n")


def _channel(path: Path) -> None:
    x_i = x25519.X25519PrivateKey.generate()
    x_r = x25519.X25519PrivateKey.generate()
    kem_i = mlkem.MLKEM768PrivateKey.generate()
    ss_kem, ct = kem_i.public_key().encapsulate()
    hello_i = MAGIC + x_i.public_key().public_bytes_raw() + kem_i.public_key().public_bytes_raw()
    hello_r = MAGIC + x_r.public_key().public_bytes_raw() + ct
    key_i2r, key_r2i, session_id = derive_keys(
        x_i.exchange(x_r.public_key()), ss_kem, hello_i, hello_r
    )
    vector = {
        "x25519_sk_initiator": x_i.private_bytes_raw().hex(),
        "x25519_sk_responder": x_r.private_bytes_raw().hex(),
        "mlkem768_seed_initiator": kem_i.private_bytes_raw().hex(),
        "hello_i": hello_i.hex(),
        "hello_r": hello_r.hex(),
        "key_i2r": key_i2r.hex(),
        "key_r2i": key_r2i.hex(),
        "session_id": session_id.hex(),
        "frame0_plaintext": FRAME_PLAINTEXT.hex(),
        "frame0_i2r": ChaCha20Poly1305(key_i2r).encrypt(_nonce(0), FRAME_PLAINTEXT, MAGIC).hex(),
    }
    path.write_text(json.dumps(vector, indent=2) + "\n")


def _session_proof(path: Path) -> None:
    initiator = KeyPair.from_secret_bytes(bytes.fromhex(SIGNATURE_VECTOR["secret_bytes"]))
    responder_public = KeyPair.generate().public_bytes()
    session_id = bytes.fromhex(json.loads((HERE / "channel_v1.json").read_text())["session_id"])
    message = session_proof_message(True, session_id, initiator.public_bytes(), responder_public)
    vector = {
        "session_id": session_id.hex(),
        "initiator_public": initiator.public_bytes().hex(),
        "responder_public": responder_public.hex(),
        "context": AUTH_CONTEXT.hex(),
        "initiator_proof_message": message.hex(),
        "initiator_proof": _sign(initiator, message, AUTH_CONTEXT).hex(),
    }
    path.write_text(json.dumps(vector, indent=2) + "\n")


_write("keystore_v1.json", _keystore)
_write("channel_v1.json", _channel)
_write("session_proof_v1.json", _session_proof)
